---
language: python
python: "2.7"

addons:
    postgresql: "9.6"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq python-apt python-pycurl

install:
  - pip install ansible
  - echo -e 'localhost    ansible_connection=local' > tests/inventory
  - echo -e '[defaults]\nroles_path = ../\nhostfile = ./tests/inventory' > ansible.cfg

script:
  - ansible-playbook --syntax-check tests/role.yml
  - ansible-playbook --sudo -v --diff -e become_method_to_use=sudo tests/role.yml
  - >
    ansible-playbook --sudo -e become_method_to_use=sudo tests/role.yml
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)
